sudo: required
services: 
  - docker

before_install:
  - docker build -t sdanaher/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sdanaher/docker-react npm run test -- --coverage

# script:
#   - docker run -e CI=true USERNAME/docker-react npm run test -- --coverage